databases:
  - name: makemusic_production
    databaseName: makemusic_production
    user: makemusic

services:
  - type: web
    name: makemusic
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: makemusic_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
